apiVersion: v2
name: ping-directory-wrapper
description: A Helm chart for PingDirectory
type: application
version: 1.0.0
appVersion: "10.1.0"
dependencies:
  - name: ping-devops
    version: 0.11.17
    repository: https://helm.pingidentity.com/
