apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pingdirectory-pdb
  namespace: pd-dev-ns
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pingdirectory
      app.kubernetes.io/instance: gcp-uscentral-pd
